version: 2
jobs:
  build:
    deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "f8:8b:bb:1e:0d:88:dd:94:06:fd:f5:d1:6f:be:63:9d"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/chenpoyi/job-box.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
